### ISSUE TITLE
[RFC] Rename 'new' to 'create'

### ISSUE THREAD

**Issue by kolyshkin** [xemul/mosaic#20]
All the actions with volumes are verbs, but 'new' is an adjective.

I suggest using `make` or `create`. Create sounds better to me as it's closer to clone, and `create` and `clone` are the only two possible ways to make a new volume.

**Comment by xemul** [comment]
Let's make it create.

**Comment by kolyshkin** [comment]
With merged commit 897c667042b4 the issue is now resolved.
