### ISSUE TITLE
Commit 4bc1e42 breaks mosaic_open()

### ISSUE THREAD

**Issue by kolyshkin** [xemul/mosaic#23]
In commit 4bc1e42 there is a call to readlink(). Note that readlink() only works for symbolic links and returns -1 for other types of files (i.e. non-symlinks). Result is:

```
[root@kir-tpad test-rm-me-ALqR1prS]# ../../moctl/moctl ./plain.mos mount - mmnt
mosaic.c/68:ERROR: Path  doesn't look like mosaic config
Error opening mosaic ./plain.mos
```

I can think of a few ways to fix it, but first I need to understand why you need it in the first place. I don't quite understand the explanation, what I can understand is you want to have some sort of unique ID. The problem is a file name (with the path and the suffix stripped) is not a unique ID. An absolute file name can be. A pair of device + inode can be.

So, back to ways to fix this are:
1. Use stat() to see if name is symlink, and call readlink() only if it is.
2. Use realpath() instead of readlink(). This would work (and maybe you had that in mind) but it seems worthless as the next step is discarding the path to the file.
3. Use something else as ID. I suggest an absolute path name.

**Comment by kolyshkin** [comment]
I guess we can close the issue now, but please comment on the question about unique ID.

**Comment by xemul** [comment]
The intention was not to create a unique ID of a mosaic, but just to introduce names. If mosaic is opened by name (main case) then the file with the same name is to be looked-up in "default" directory.

There should be, however, backward conversion. When you open a mosaic by file name libmosaic should "calculate" its name. The name, as from the first paragraph, is it's filename's basename minus the .mos suffix. But you may create a symlink on your config file and opent _it_. Thus we need to get the _real_ file name to drain the name from.
